### ISSUE TITLE
Version selection problem

### ISSUE THREAD

**Issue by tkdchen** [jerop/tkn#1]
[Version](https://github.com/jerop/tkn#version) section tells:

>jerop/tkn installs the latest version of tkn by default

but, it defaults to select v0.18.0.

Meanwhile, `latest` in [description](https://github.com/jerop/tkn/blob/main/action.yml#L8) can confuse readers because no release version `latest` there.

**Comment by jerop** [comment]
Fixed in https://github.com/jerop/tkn/pull/2
